---
- name: Master Node  
  hosts: 127.0.0.1
  connection: local
  user: root
  vars_files:
    - vars/vars.yml
  vars:
        username: desmotes
  
  tasks:
  - name: Adding desmotes user
    user: name={{username}} shell=/bin/bash groups=root append=yes password={{desmotes}}
    sudo: yes

  - debug: msg="Pass {{ desmotes }}"

  - name: Placing RSA key
    authorized_key: user={{username}} key="{{ lookup('file', 'id_rsa.pub') }}"
    sudo: yes


